/**
 * test/charts.test.js — Chart rendering pipeline tests
 *
 * Tests:
 * 1. Build: Graph blocks extracted into fs.json with correct structure
 * 2. HTML: Canvas elements rendered into content HTML with data-graph-id
 * 3. Data: Graph data matches charts.js renderAll() expectations
 * 4. Canvas-Graph pairing: Each canvas data-graph-id has matching graph data
 * 5. Multiple graphs: Works across multiple pages
 * 6. Bundled output: dist/js/charts.js has all required functions
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

let passed = 0;
let failed = 0;

function assert(condition, name) {
  if (condition) {
    console.log(`  ✓ ${name}`);
    passed++;
  } else {
    console.log(`  ✗ ${name}`);
    failed++;
  }
  return condition;
}

function section(name) {
  console.log(`\n${'='.repeat(60)}`);
  console.log(`  ${name}`);
  console.log('='.repeat(60));
}

// ── Helpers ──────────────────────────────────────────────────────────────────
function loadFsJson() {
  const fsPath = path.join(root, 'dist', 'fs.json');
  if (!fs.existsSync(fsPath)) {
    console.log('  ✗ fs.json not found — run `npm run build` first');
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(fsPath, 'utf-8'));
}

/**
 * Simulate what charts.js renderAll() does:
 * For each graph, build the Chart.js config object.
 */
function buildChartConfig(graph) {
  return {
    type: graph.type || 'line',
    data: {
      labels: graph.labels || [],
      datasets: graph.datasets || []
    },
    options: graph.options || {}
  };
}

// ── Test 1: Build pipeline extracts graphs ──────────────────────────────────
function testBuildPipeline() {
  section('Test 1: Build pipeline — graph extraction');

  const fsData = loadFsJson();
  const content = fsData.content;

  const readme = content['/docs/readme.md'];
  assert(!!readme, '/docs/readme.md content exists');
  assert(!!readme.graphs, 'readme.md has graphs field');
  assert(Array.isArray(readme.graphs), 'graphs is an array');
  assert(readme.graphs.length === 1, 'readme.md has exactly 1 graph');

  const graph = readme.graphs[0];
  assert(graph.id === 'g_0', 'graph id is g_0');
  assert(graph.type === 'bar', 'graph type is bar');
  assert(graph.title === 'TerminalX Performance', 'graph title matches');
  assert(Array.isArray(graph.labels), 'graph has labels array');
  assert(graph.labels.length === 4, 'graph has 4 labels');
  assert(graph.labels[0] === 'Build', 'first label is Build');
  assert(Array.isArray(graph.datasets), 'graph has datasets array');
  assert(graph.datasets.length === 1, 'graph has 1 dataset');
  assert(graph.datasets[0].label === 'Score', 'dataset label is Score');
  assert(graph.datasets[0].data.length === 4, 'dataset has 4 data points');

  // Portfolio page also has a graph
  const portfolio = content['/projects/portfolio/overview.md'];
  assert(!!portfolio, '/projects/portfolio/overview.md exists');
  assert(!!portfolio.graphs, 'portfolio.md has graphs');
  assert(portfolio.graphs.length === 1, 'portfolio has 1 graph');
  assert(portfolio.graphs[0].type === 'line', 'portfolio graph is line type');
  assert(portfolio.graphs[0].title === 'Portfolio Growth', 'portfolio graph title matches');
  assert(portfolio.graphs[0].labels.length === 7, 'portfolio graph has 7 labels');
}

// ── Test 2: HTML rendering includes canvas ───────────────────────────────────
function testHtmlRendering() {
  section('Test 2: HTML rendering — canvas elements');

  const fsData = loadFsJson();
  const content = fsData.content;

  const readme = content['/docs/readme.md'];
  assert(!!readme.html, 'readme has html field');
  assert(readme.html.includes('<canvas'), 'readme HTML contains canvas tag');
  assert(readme.html.includes('data-graph-id="g_0"'), 'canvas has data-graph-id="g_0"');
  assert(readme.html.includes('graph-canvas'), 'canvas has graph-canvas class');

  // Verify the canvas is inside a <p> tag (as generated by the transformer)
  assert(readme.html.includes('<p><canvas'), 'canvas is wrapped in paragraph');

  // Portfolio page
  const portfolio = content['/projects/portfolio/overview.md'];
  assert(portfolio.html.includes('<canvas'), 'portfolio HTML contains canvas tag');
  assert(portfolio.html.includes('data-graph-id="g_0"'), 'portfolio canvas has data-graph-id');
}

// ── Test 3: Data structure matches charts.js expectations ───────────────────
function testDataStructure() {
  section('Test 3: Data structure — charts.js compatibility');

  const fsData = loadFsJson();
  const content = fsData.content;

  const graphFiles = Object.entries(content)
    .filter(([k, v]) => v.graphs && v.graphs.length > 0);

  assert(graphFiles.length >= 2, `Found ${graphFiles.length} files with graphs`);

  for (const [file, data] of graphFiles) {
    for (const graph of data.graphs) {
      const config = buildChartConfig(graph);
      assert(config.type === graph.type || config.type === 'line',
        `${file}: config.type is valid (${config.type})`);
      assert(config.data.labels.length > 0,
        `${file}: config.data.labels is non-empty (${config.data.labels.length})`);
      assert(config.data.datasets.length > 0,
        `${file}: config.data.datasets is non-empty (${config.data.datasets.length})`);

      for (const ds of config.data.datasets) {
        assert(Array.isArray(ds.data), `${file}: dataset.data is array`);
        assert(ds.data.length > 0, `${file}: dataset.data is non-empty`);
      }
    }
  }

  console.log(`  ℹ All ${graphFiles.reduce((s, [, v]) => s + v.graphs.length, 0)} graphs validated`);
}

// ── Test 4: Canvas-Graph pairing ─────────────────────────────────────────────
function testCanvasGraphPairing() {
  section('Test 4: Canvas-Graph pairing — every canvas has matching graph');

  const fsData = loadFsJson();
  const content = fsData.content;

  let totalCanvases = 0;
  let totalGraphs = 0;

  for (const [file, data] of Object.entries(content)) {
    if (!data.html) continue;

    const canvasMatches = data.html.match(/<canvas[^>]+>/g) || [];
    const graphList = data.graphs || [];

    totalCanvases += canvasMatches.length;
    totalGraphs += graphList.length;

    // Each canvas data-graph-id must have a matching graph entry
    for (const match of canvasMatches) {
      const idMatch = match.match(/data-graph-id="([^"]+)"/);
      assert(!!idMatch, `${file}: canvas has data-graph-id attribute`);

      if (idMatch) {
        const graphId = idMatch[1];
        const graph = graphList.find(g => g.id === graphId);
        assert(!!graph, `${file}: canvas ${graphId} has matching graph data`);

        if (graph) {
          assert(graph.type === 'bar' || graph.type === 'line',
            `${file}: graph ${graphId} type is valid`);
          assert(Array.isArray(graph.labels),
            `${file}: graph ${graphId} has labels`);
          assert(Array.isArray(graph.datasets),
            `${file}: graph ${graphId} has datasets`);
        }
      }
    }
  }

  assert(totalCanvases >= 2, `Found ${totalCanvases} canvas elements across pages`);
  assert(totalGraphs >= 2, `Found ${totalGraphs} graph definitions across pages`);
}

// ── Test 5: Bundled output ───────────────────────────────────────────────────
function testBundledOutput() {
  section('Test 5: Bundled output — dist/js/charts.js');

  const bundledPath = path.join(root, 'dist', 'js', 'charts.js');
  assert(fs.existsSync(bundledPath), 'dist/js/charts.js exists');

  const bundledCode = fs.readFileSync(bundledPath, 'utf-8');
  assert(bundledCode.includes('initGraphs'), 'bundled charts has initGraphs');
  assert(bundledCode.includes('ensureChartJs'), 'bundled charts has ensureChartJs');
  assert(bundledCode.includes('renderAll'), 'bundled charts has renderAll');
  assert(bundledCode.includes('chart.js@4'), 'bundled charts loads Chart.js v4');
  assert(bundledCode.includes('pendingGraphs'), 'bundled charts has pendingGraphs');
  assert(bundledCode.includes('new Chart('), 'bundled charts creates Chart instances');
  assert(bundledCode.includes('getContext'), 'bundled charts gets 2d context');

  console.log(`  ℹ Bundled size: ${(bundledCode.length / 1024).toFixed(1)}KB`);
}

// ── Test 6: Source module exports ────────────────────────────────────────────
function testSourceModule() {
  section('Test 6: Source module — shell/js/charts.js');

  const chartsPath = path.join(root, 'shell', 'js', 'charts.js');
  assert(fs.existsSync(chartsPath), 'charts.js exists in shell/js/');

  const chartsCode = fs.readFileSync(chartsPath, 'utf-8');
  assert(chartsCode.includes('export async function initGraphs'), 'initGraphs is exported');
  assert(chartsCode.includes('document.querySelector'), 'charts.js queries DOM');
  assert(chartsCode.includes('data-graph-id'), 'charts.js queries by data-graph-id');
  assert(chartsCode.includes('getContext'), 'charts.js gets 2d context');
  assert(chartsCode.includes('new Chart'), 'charts.js instantiates Chart');

  // Verify the lazy-load mechanism
  assert(chartsCode.includes('chart.js@4'), 'loads Chart.js v4');
  assert(chartsCode.includes('document.head.appendChild'), 'appends script to head');
  assert(chartsCode.includes('script.onload'), 'has onload handler');
}

// ── Run all tests ────────────────────────────────────────────────────────────
function runAll() {
  console.log('\n╔══════════════════════════════════════════════════════════╗');
  console.log('║   TerminalX Chart Rendering Tests                       ║');
  console.log('╚══════════════════════════════════════════════════════════╝\n');

  try {
    testBuildPipeline();
    testHtmlRendering();
    testDataStructure();
    testCanvasGraphPairing();
    testBundledOutput();
    testSourceModule();
  } catch (e) {
    console.log(`\n  ✗ Test suite ERROR: ${e.message}`);
    console.log(`  ${e.stack}`);
    failed++;
  }

  console.log('\n' + '='.repeat(60));
  console.log(`  Results: ${passed} passed, ${failed} failed, ${passed + failed} total`);
  console.log('='.repeat(60));

  if (failed === 0) {
    console.log('\n  ✓ All tests passed! Charts pipeline is working.\n');
  } else {
    console.log(`\n  ✗ ${failed} test(s) failed. Review above.\n`);
  }

  process.exit(failed > 0 ? 1 : 0);
}

runAll();
